// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type BotSetting struct {
	ID           int32        `json:"id"`
	Registration sql.NullBool `json:"registration"`
}

type ReadingLog struct {
	Userid      string       `json:"userid"`
	Username    string       `json:"username"`
	Date        time.Time    `json:"date"`
	MinutesRead int32        `json:"minutes_read"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type User struct {
	Userid     string         `json:"userid"`
	Username   string         `json:"username"`
	Registered sql.NullBool   `json:"registered"`
	Language   sql.NullString `json:"language"`
	State      sql.NullString `json:"state"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}
